baseURL = "https://crismotinha.github.io"
disqusShortname = ""
languageCode = "pt-br"
paginate = "5"
summaryLength = "10"
theme = "northendlab-hugo"
title = "Cris Motinha"
[[menu.footer]]
URL = "contact"
name = "Contact"
weight = 1
[[menu.footer]]
URL = "posts"
name = "Posts"
weight = 2
[[menu.main]]
URL = "about"
name = "About Me"
weight = 1
[[menu.main]]
URL = "posts"
name = "Posts"
weight = 2
[[menu.main]]
URL = "food"
name = "Food"
weight = 3
[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]
[params]
author = "Cris Motinha"
contact_form_action = "#"
copyright = "&copy; 2020 [Gethugothemes](https://gethugothemes.com) All Rights Reserved"
description = "My personal website"
google_tag_manager = ""
home = "Home"
logo = "/images/logo3.png"
[params.banner]
bgImage = "images/banner/banner-bg.svg"
image = "/images/banner.png"
title = "Hi, I'm Cris Motinha"
[params.cookies]
enable = true
expire_days = 2
[params.cta]
description = "Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus."
enable = false
image = "images/hugo-muscot.svg"
title = "Get the best hugo templates"
[params.cta.button]
enable = true
label = "Visit Here"
link = "https://gethugothemes.com/shop/"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = ""
[params.search]
enable = true
[[params.social]]
icon = "ti-github"
link = "https://github.com/crismotinha"
[[params.social]]
icon = "ti-linkedin"
link = "https://www.linkedin.com/in/cristina-motinha"
